# Generated by Django 4.2.5 on 2023-10-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('account_number', models.CharField(max_length=255)),
                ('ifsc', models.CharField(max_length=255)),
                ('bank_user_id', models.IntegerField()),
                ('nominee', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FraudCase',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('transaction_id', models.IntegerField()),
                ('logtime', models.DateTimeField(auto_now_add=True)),
                ('isfraud', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('pincode', models.IntegerField()),
                ('mobile_no', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('logtime', models.DateTimeField(auto_now_add=True)),
                ('from_user_id', models.IntegerField()),
                ('to_user_id', models.IntegerField()),
                ('from_user_account_id', models.CharField(max_length=255)),
                ('to_user_account_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='userResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('rating', models.CharField(max_length=255)),
                ('response', models.TextField()),
            ],
        ),
    ]
